import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;
class Zadanie_listy2{
    public static void main(String[] args){
        Tory t = new Tory("Adelaide Street Circuit", "1985", "Keke Rosberg");
        Random r = new Random();
        Scanner sc = new Scanner(System.in);
        String b = "";
        ArrayList<String> list = new ArrayList<>();
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Ain-Diab Circuit", "1958", "Stirling Moss");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Aintree Motor Racing Circuit", "1955", "Stirling Moss");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Albert Park Circuit", "1996", "Damon Hill");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autódromo Internacional do Algarve", "2020", "Lewis Hamilton");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("AVUS", "1959", "Tony Brooks");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Bahrain International Circuit", "2004", "Michael Schumacher");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Baku City Circuit", "2016", "Nico Rosberg");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit de Barcelona-Catalunya", "1991", "Nigel Mansell");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuito da Boavista", "1958", "Stirling Moss");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Brands Hatch", "1964", "Nelson Piquet");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit Bremgarten", "1950", "Giuseppe Farina");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Buddh International Circuit", "2011", "Sebastian Vettel");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Bugatti Circuit", "1967", "Jack Brabham");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Caesars Palace", "1981", "Alan Jones");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Charade Circuit", "1965", "Jim Clark");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit of the Americas", "2012", "Lewis Hamilton");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Detroit Street Circuit", "1982", "John Watson");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Dijon-Prenois", "1974", "Niki Lauda");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Donington Park", "1993", "Ayrton Senna");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autodromo Enzo e Dino Ferrari", "1980", "Nelson Piquet");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autódromo do Estoril", "1984", "Alain Prost");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Fair Park", "1984", "Keke Rosberg");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Fuji International Speedway", "1976", "Mario Andretti");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit Gilles Villeneuve", "1978", "Gilles Villeneuve");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autódromo Hermanos Rodríguez", "1963", "Jim Clark");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Hockenheimring", "1970", "Jochen Rindt");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Hungaroring", "1986", "Nelson Piquet");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Indianapolis Motor Speedway", "1950", "Michael Schumacher");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Istanbul Park", "2005", "Kimi Räikkönen");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autódromo Internacional Nelson Piquet", "1978", "Carlos Reutemann");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuito del Jarama", "1968", "Graham Hill");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Jeddah Corniche Circuit", "2021", "Lewis Hamilton");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuito Permanente de Jerez", "1986", "Ayrton Senna");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autódromo José Carlos Pace", "1973", "Emerson Fittipaldi");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Korea International Circuit", "2010", "Fernando Alonso");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Kyalami Circuit", "1967", "Pedro Rodríguez");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Long Beach Street Circuit", "1976", "Clay Regazzoni");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Losail International Circuit", "2021", "Max Verstappen");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit de Nevers Magny-Cours", "1991", "Nigel Mansell");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Marina Bay Street Circuit", "2008", "Fernando Alonso");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Miami International Autodrome", "2022", "Charles Leclerc");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Monsanto Park", "1959", "Stirling Moss");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Mugello Circuit", "2020", "Lewis Hamilton");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit de Monaco", "1950", "Juan Manuel Fangio");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit Mont-Tremblant", "1968", "Denny Hulme");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Mosport International Raceway", "1967", "Jack Brabham");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Montjuïc Circuit", "1969", "Jackie Stewart");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autodromo Nazionale di Monza", "1950", "Lewis Hamilton");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Nivelles-Baulers", "1972", "Emerson Fittipaldi");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Nürburgring", "1951", "Alberto Ascari");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Autódromo Oscar Alfredo Gálvez", "1953", "Alberto Ascari");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit Paul Ricard", "1971", "Jackie Stewart");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Pedralbes Circuit", "1951", "Juan Manuel Fangio");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Pescara Circuit", "1957", "Stirling Moss");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Phoenix Circuit", "1989", "Alain Prost");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Prince George Circuit", "1962", "Graham Hill");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Red Bull Ring", "1970", "Jacky Ickx");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Reims-Gueux", "1950", "Juan Manuel Fangio");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Riverside International Raceway", "1960", "Stirling Moss");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Rouen-Les-Essarts", "1952", "Alberto Ascari");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Scandinavian Raceway", "1973", "Denny Hulme");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Sebring International Raceway", "1959", "Bruce McLaren");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Sepang International Circuit", "1999", "Eddie Irvine");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Shanghai International Circuit", "2004", "Rubens Barrichello");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Silverstone Circuit", "1965", "Giuseppe Farina");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Sochi Autodrom", "2014", "Lewis Hamilton");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit de Spa-Francorchamps", "1950", "Juan Manuel Fangio");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Suzuka International Racing Course", "1987", "Gerhard Berger");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Okayama International Circuit", "1994", "Michael Schumacher");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Valencia Street Circuit", "2008", "Felipe Massa");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Watkins Glen", "1961", "Innes Ireland");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Yas Marina Circuit", "2009", "Sebastian Vettel");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit Park Zandvoort", "1952", "Alberto Ascari");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Zeltweg Airfield", "1964", "Lorenzo Bandini");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());
        t = new Tory("Circuit Zolder", "1973", "Jackie Stewart");
        list.add(t.getTor());
        list.add(t.getData());
        list.add(t.getWygrany());

        t.menu();
        int a = sc.nextInt();
        if (a == 1){
            for(int i=0; i<list.size(); i+=3){
                System.out.println(list.get(i));
            }
        } else if (a == 2){
                for(int i=2; i<list.size(); i+=3){
                    if (!b.contains(list.get(i))){
                        System.out.println(list.get(i));
                    }
                    b = b+list.get(i);
                }
        } else if (a == 3){
            int wgr = 0;
            String odp = "";
            for(int i = 2; i<list.size(); i+=3){
                String wgr1 = list.get(i);
                int wgr2 = 0;
                for(int j=2; j<list.size();j++){
                    if(odp.equals(list.get(j))){
                        wgr2++;
                    }
                }
                if(wgr2>=wgr){
                    odp=wgr1;
                    wgr = wgr2;
                }
            }
            System.out.println(odp);
        } else {
            System.out.println("Wybrano złą opcje");
        }
    }
}